//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int IdComentario { get; set; }
        public string Texto { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
    }
}
